---
- name: playbook to enable webserver ntp service and postfix
  hosts: all
  tasks: 
    - name: webserver is enabled
      service:
        name: httpd
        enabled: true
    - name: NTP server is enabled
      service: 
        name: chronyd
        enabled: true

    - name: postfix is enabled
      service:
        name: postfix
        enabled: true
